name = "Vinchenzo"
license = "CC0"
licenselink = "https://github.com/jdekarske/vinchenzo/edit/main/LICENSE"
description = ""
homepage = "https://github.com/jdekarske/vinchenzo"
tags = ["simple", "responsive", "hugo"]
features = []
min_version = "0.92.2"

[author]
  name = "Jason Dekarske"
  homepage = "https://www.jasondekarske.com"
